# Generated by Django 5.2 on 2025-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("content_id", models.UUIDField(null=True, verbose_name="Object ID")),
                ("timestamp", models.DateTimeField()),
                ("api_data", models.JSONField(null=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
