# Generated by Django 5.2.2 on 2025-06-04 19:35

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("asset", "Asset"),
                            ("episode", "Episode"),
                            ("franchise", "Franchise"),
                            ("season", "Season"),
                            ("show", "Show"),
                            ("special", "Special"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("content_id", models.UUIDField(null=True, verbose_name="Content ID")),
                ("timestamp", models.DateTimeField()),
                ("api_data", models.JSONField(null=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
