# Generated by Django 5.2.12 on 2026-07-03 09:27

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def update_changelogs(apps, schema_editor):
    ChangeLog = apps.get_model("changelog", "ChangeLog")
    ContentRecord = apps.get_model("record", "ContentRecord")
    content_record_ids = ContentRecord.objects.values_list("content_id", flat=True)
    ChangeLog.objects.filter(object_id__in=content_record_ids).update(
        mm_content_id=models.F("object_id")
    )
    ChangeLog.objects.filter(mm_content__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
        ("franchise", "0003_remove_franchise_api_endpoint_and_more"),
        ("show", "0014_remove_show_api_endpoint_remove_show_audience_and_more"),
        ("season", "0019_remove_season_api_endpoint_and_more"),
        ("special", "0015_remove_special_api_endpoint_and_more"),
        ("episode", "0019_remove_episode_api_endpoint_and_more"),
        ("asset", "0011_remove_asset_api_endpoint_remove_asset_asset_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changelog",
            name="api_data",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="api_status",
        ),
        migrations.RenameField(
            model_name="changelog", old_name="content_id", new_name="object_id"
        ),
        migrations.AddField(
            model_name="changelog",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(update_changelogs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="changelog",
            name="object_id",
        ),
    ]
