# Generated by Django 6.0.5 on 2026-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelog",
            name="deleted",
            field=models.DateTimeField(null=True),
        ),
    ]
