# Generated by Django 6.0.5 on 2026-07-06 18:50

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0002_remove_changelog_api_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelog",
            name="deleted",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Set from the entry timestamp when the latest changelog"
                    " action is 'delete'."
                ),
                null=True,
                verbose_name="Deleted",
            ),
        ),
    ]
