[tool.poetry]
python
name='django-pbsmmapi'
version='0.2.5'
description="Django models that import content from the PBS MediaManager API"
readme=README.md
license='MIT License, see LICENSE'
authors=['Bob Donahue']
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 4.0',
    'Framework :: Django :: 4.1',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
django = "*"
requests = "*"
python-dateutil = "*"
pytz = "*"
