# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmspecial',
            name='encored_on',
        ),
    ]
