# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_remove_pbsmmspecial_encored_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmspecialasset',
            name='is_default_asset',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Is Default Asset'),
        ),
    ]
