# Generated by Django 4.0.5 on 2022-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0007_remove_pbsmmspecialasset_canonical_image_type_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmspecialasset',
            name='images_json',
            field=models.JSONField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Images'),
        ),
    ]
