# Generated by Django 5.2.12 on 2026-06-18 10:32

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def link_specials(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Special = apps.get_model("special", "Special")
    content_records = {
        record.content_id: record
        for record in ContentRecord.objects.filter(api_data__data__type="special")
    }
    specials = list(Special.objects.filter(object_id__isnull=False))
    for special in specials:
        special.mm_content = content_records.get(special.object_id)
    Special.objects.bulk_update(specials, ["mm_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
        ("special", "0014_special_provisional"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_specials, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="special",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="special",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="special",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="special",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="special",
            name="json",
        ),
        migrations.RemoveField(
            model_name="special",
            name="language",
        ),
        migrations.RemoveField(
            model_name="special",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="special",
            name="links",
        ),
        migrations.RemoveField(
            model_name="special",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="special",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="special",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="special",
            name="show_api_id",
        ),
        migrations.RemoveField(
            model_name="special",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="special",
            name="updated_at",
        ),
    ]
