# Generated by Django 5.2.12 on 2026-06-18 10:32

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


def link_specials(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Special = apps.get_model("special", "Special")
    content_record_map = dict(
        ContentRecord.objects.filter(api_data__data__type="special").values_list(
            "content_id", "pk"
        )
    )

    batch_size = 1000
    batch = []

    for special in Special.objects.filter(object_id__isnull=False).iterator(
        chunk_size=batch_size
    ):
        content_record_pk = content_record_map.get(special.object_id)
        if content_record_pk:
            special.mm_content_id = content_record_pk
            batch.append(special)
            if len(batch) >= batch_size:
                Special.objects.bulk_update(batch, ["mm_content"])
                batch.clear()

    if batch:
        Special.objects.bulk_update(batch, ["mm_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
        ("special", "0014_special_provisional"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_specials, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="special",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="special",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="special",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="special",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="special",
            name="json",
        ),
        migrations.RemoveField(
            model_name="special",
            name="language",
        ),
        migrations.RemoveField(
            model_name="special",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="special",
            name="links",
        ),
        migrations.RemoveField(
            model_name="special",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="special",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="special",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="special",
            name="show_api_id",
        ),
        migrations.RemoveField(
            model_name="special",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="special",
            name="updated_at",
        ),
    ]
