# Generated by Django 5.2.17 on 2026-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("special", "0015_remove_special_api_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="special",
            options={
                "base_manager_name": "objects",
                "verbose_name": "PBS MM Special",
                "verbose_name_plural": "PBS MM Specials",
            },
        ),
    ]
