# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteasset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmremoteasset',
            name='title_sortable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sortable Title'),
        ),
    ]
