# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBSMMEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Not set by API', verbose_name='Created On')),
                ('date_last_api_update', models.DateTimeField(help_text='Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text='If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('link_to_api_record', models.URLField(blank=True, help_text='Endpoint to original record from the API', null=True, verbose_name='Link to API Record')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_sortable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sortable Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description_long', models.TextField(verbose_name='Long Description')),
                ('description_short', models.TextField(verbose_name='Short Description')),
                ('updated_at', models.DateTimeField(blank=True, help_text='API record modified date', null=True, verbose_name='Updated At')),
                ('premiered_on', models.DateTimeField(blank=True, null=True, verbose_name='Premiered On')),
                ('nola', models.CharField(blank=True, max_length=8, null=True, verbose_name='NOLA Code')),
                ('funder_message', models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Funder Message')),
                ('links', models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Links')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language')),
                ('encored_on', models.DateTimeField(blank=True, null=True, verbose_name='Encored On')),
            ],
            options={
                'verbose_name': 'PBS Medio Manager Episode',
                'verbose_name_plural': 'PBS Media Manager Episodes',
            },
        ),
    ]
