# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmepisode',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordinal'),
        ),
        migrations.AddField(
            model_name='pbsmmepisode',
            name='segment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Segment'),
        ),
    ]
