# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmepisode',
            name='extra_description',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Description'),
        ),
    ]
