# Generated by Django 4.0.5 on 2022-06-22 18:29

import json

from django.db import migrations


def move_string_to_json(apps, schema_editor):
    PBSMMEpisodeAsset = apps.get_model('episode', 'PBSMMEpisodeAsset')

    for asset in PBSMMEpisodeAsset.objects.all():
        asset.images_json = json.loads(asset.images)
        asset.save()


def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0009_pbsmmepisodeasset_images_json'),
    ]

    operations = [
        migrations.RunPython(move_string_to_json, undo),
    ]
