# Generated by Django 4.0.6 on 2022-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0010_pbsmmepisodeasset_images_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmepisode',
            name='segment',
        ),
    ]
