# Generated by Django 5.2 on 2025-04-15 18:00

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0014_rename_pbsmmepisode_episode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
