# Generated by Django 5.2.12 on 2026-06-17 11:37

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def link_episodes(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Episode = apps.get_model("episode", "Episode")
    content_records = {
        record.content_id: record
        for record in ContentRecord.objects.filter(api_data__data__type="episode")
    }
    episodes = list(Episode.objects.filter(object_id__isnull=False))
    for episode in episodes:
        episode.mm_content = content_records[episode.object_id]
    Episode.objects.bulk_update(episodes, ["mm_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0018_auto_increment_ordinal"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_episodes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="episode",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="encored_on",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="json",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="language",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="links",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="season_api_id",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="updated_at",
        ),
    ]
