# Generated by Django 5.2.12 on 2026-06-17 11:37

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


def link_episodes(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Episode = apps.get_model("episode", "Episode")
    content_record_map = dict(
        ContentRecord.objects.filter(api_data__data__type="episode").values_list(
            "content_id", "pk"
        )
    )

    batch_size = 1000
    batch = []

    for episode in Episode.objects.filter(object_id__isnull=False).iterator(
        chunk_size=batch_size
    ):
        content_record_pk = content_record_map.get(episode.object_id)
        if content_record_pk:
            episode.mm_content_id = content_record_pk
            batch.append(episode)
            if len(batch) >= batch_size:
                Episode.objects.bulk_update(batch, ["mm_content"])
                batch.clear()

    if batch:
        Episode.objects.bulk_update(batch, ["mm_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("episode", "0018_auto_increment_ordinal"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_episodes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="episode",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="encored_on",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="json",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="language",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="links",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="season_api_id",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="updated_at",
        ),
    ]
