# Generated by Django 5.2.17 on 2026-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episode", "0019_remove_episode_api_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={
                "base_manager_name": "objects",
                "verbose_name": "PBS MM Episode",
                "verbose_name_plural": "PBS MM Episodes",
            },
        ),
    ]
