# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBSMMLightAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightRemoteAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
