# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmlightasset',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightcollection',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightepisode',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightfranchise',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightremoteasset',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightseason',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightshow',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
        migrations.AddField(
            model_name='pbsmmlightspecial',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
    ]
