# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmseason',
            name='ingest_episodes',
            field=models.BooleanField(default=False, help_text='Also ingest all Episodes (for each Season)', verbose_name='Ingest Episodes'),
        ),
    ]
