# Generated by Django 4.0.5 on 2022-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0008_remove_pbsmmseason_canonical_image_type_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmseason',
            name='images_json',
            field=models.JSONField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='pbsmmseasonasset',
            name='images_json',
            field=models.JSONField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Images'),
        ),
    ]
