# Generated by Django 4.0.5 on 2022-06-22 18:39
import json

from django.db import migrations


def move_string_to_json(apps, schema_editor):
    PBSMMSeason = apps.get_model('season', 'PBSMMSeason')
    PBSMMSeasonAsset = apps.get_model('season', 'PBSMMSeasonAsset')

    for season in PBSMMSeason.objects.all():
        season.images_json = json.loads(season.images)
        season.save()

    for asset in PBSMMSeasonAsset.objects.all():
        asset.images_json = json.loads(asset.images)
        asset.save()


def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0009_pbsmmseason_images_json_pbsmmseasonasset_images_json'),
    ]

    operations = [
        migrations.RunPython(move_string_to_json, undo),
    ]
