# Generated by Django 4.0.6 on 2022-07-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0010_pbsmmseason_images_json_pbsmmseasonasset_images_json'),
        ('asset', '0002_move_assets_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PBSMMSeasonAsset',
        ),
    ]
