# Generated by Django 5.2.12 on 2026-06-17 13:20

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


def link_seasons(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Season = apps.get_model("season", "Season")
    content_record_map = dict(
        ContentRecord.objects.filter(api_data__data__type="season").values_list(
            "content_id", "pk"
        )
    )

    batch_size = 1000
    batch = []

    for season in Season.objects.filter(object_id__isnull=False).iterator(
        chunk_size=batch_size
    ):
        content_record_pk = content_record_map.get(season.object_id)
        if content_record_pk:
            season.mm_content_id = content_record_pk
            batch.append(season)
            if len(batch) >= batch_size:
                Season.objects.bulk_update(batch, ["mm_content"])
                batch.clear()

    if batch:
        Season.objects.bulk_update(batch, ["mm_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
        ("season", "0018_auto_increment_ordinal"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_seasons, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="season",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="season",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="season",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="season",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="season",
            name="images",
        ),
        migrations.RemoveField(
            model_name="season",
            name="json",
        ),
        migrations.RemoveField(
            model_name="season",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="season",
            name="links",
        ),
        migrations.RemoveField(
            model_name="season",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="show_api_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="season",
            name="updated_at",
        ),
    ]
