# Generated by Django 5.2.17 on 2026-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("season", "0019_remove_season_api_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="season",
            options={
                "base_manager_name": "objects",
                "ordering": ["-ordinal"],
                "verbose_name": "PBS MM Season",
                "verbose_name_plural": "PBS MM Seasons",
            },
        ),
    ]
