# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_pbsmmshowasset_is_default_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmshowasset',
            name='is_default_asset',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Is Default Asset'),
        ),
    ]
