# Generated by Django 4.0.5 on 2022-06-22 18:39
import json

from django.db import migrations


def move_string_to_json(apps, schema_editor):
    PBSMMShow = apps.get_model('show', 'PBSMMShow')
    PBSMMShowAsset = apps.get_model('show', 'PBSMMShowAsset')

    for show in PBSMMShow.objects.all():
        show.images_json = json.loads(show.images)
        show.save()

    for asset in PBSMMShowAsset.objects.all():
        asset.images_json = json.loads(asset.images)
        asset.save()


def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_pbsmmshow_images_json_pbsmmshowasset_images_json'),
    ]

    operations = [
        migrations.RunPython(move_string_to_json, undo),
    ]
