# Generated by Django 5.1.7 on 2025-05-30 14:30

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0011_alter_show_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="season_ordinal",
            field=models.BooleanField(
                default=True,
                help_text="Use incrementing integer or current year when creating a Season",
                verbose_name="Season Ordinal",
            ),
        ),
    ]
