# Generated by Django 5.2.12 on 2026-06-18 10:20

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def link_shows(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Show = apps.get_model("show", "Show")
    content_records = {
        record.content_id: record
        for record in ContentRecord.objects.filter(api_data__data__type="show")
    }
    shows = list(Show.objects.filter(object_id__isnull=False))
    for show in shows:
        show.mm_content = content_records[show.object_id]
    Show.objects.bulk_update(shows, ["mm_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
        ("show", "0013_remove_show_season_ordinal_alter_show_ordinal_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_shows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="show",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="show",
            name="audience",
        ),
        migrations.RemoveField(
            model_name="show",
            name="can_embed_player",
        ),
        migrations.RemoveField(
            model_name="show",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="show",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="show",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="show",
            name="display_episode_number",
        ),
        migrations.RemoveField(
            model_name="show",
            name="episode_count",
        ),
        migrations.RemoveField(
            model_name="show",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="show",
            name="ga_event",
        ),
        migrations.RemoveField(
            model_name="show",
            name="ga_page",
        ),
        migrations.RemoveField(
            model_name="show",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="show",
            name="hashtag",
        ),
        migrations.RemoveField(
            model_name="show",
            name="images",
        ),
        migrations.RemoveField(
            model_name="show",
            name="is_excluded_from_dfp",
        ),
        migrations.RemoveField(
            model_name="show",
            name="json",
        ),
        migrations.RemoveField(
            model_name="show",
            name="language",
        ),
        migrations.RemoveField(
            model_name="show",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="show",
            name="links",
        ),
        migrations.RemoveField(
            model_name="show",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="show",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="show",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="show",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="show",
            name="sort_episodes_descending",
        ),
        migrations.RemoveField(
            model_name="show",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="show",
            name="updated_at",
        ),
    ]
