# Generated by Django 6.0.5 on 2026-07-02 13:03

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0013_remove_show_season_ordinal_alter_show_ordinal_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="deleted",
            field=models.DateTimeField(
                blank=True,
                help_text="Set from the PBS changelog timestamp when the object was deleted upstream.",
                null=True,
                verbose_name="Deleted",
            ),
        ),
    ]
