# Generated by Django 5.2.17 on 2026-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("show", "0014_remove_show_api_endpoint_remove_show_audience_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="show",
            options={
                "base_manager_name": "objects",
                "verbose_name": "PBS MM Show",
                "verbose_name_plural": "PBS MM Shows",
            },
        ),
    ]
