# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBSMMAssetCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=40, verbose_name='Profile')),
                ('url', models.URLField(verbose_name='URL')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.PBSMMAsset')),
            ],
        ),
        migrations.CreateModel(
            name='PBSMMAssetChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(blank=True, decimal_places=1, help_text='decimal field, not floating-point', max_digits=6, null=True, verbose_name='Start')),
                ('end', models.DecimalField(blank=True, decimal_places=1, help_text='decimal field, not floating-point', max_digits=6, null=True, verbose_name='Start')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.PBSMMAsset')),
            ],
        ),
    ]
