# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_pbsmmassetcaption_pbsmmassetchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmasset',
            name='object_id',
            field=models.UUIDField(blank=True, unique=True, verbose_name='Object ID'),
        ),
    ]
