# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180205_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='tags',
            field=models.TextField(blank=True, help_text='raw array', null=True, verbose_name='Tags'),
        ),
    ]
