# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_pbsmmasset_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmassetchapter',
            name='asset',
        ),
        migrations.AddField(
            model_name='pbsmmassetavailability',
            name='chapters',
            field=models.TextField(blank=True, help_text='JSON serialized object', null=True, verbose_name='Chapters'),
        ),
        migrations.DeleteModel(
            name='PBSMMAssetChapter',
        ),
    ]
