# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180205_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmassetavailability',
            name='asset',
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='availability',
            field=models.TextField(blank=True, help_text='JSON serialized Field', null=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='funder_message',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Funder Message'),
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='topics',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Topics'),
        ),
        migrations.AddField(
            model_name='pbsmmassetimage',
            name='chapters',
            field=models.TextField(blank=True, help_text='JSON serialized object', null=True, verbose_name='Chapters'),
        ),
        migrations.AlterField(
            model_name='pbsmmasset',
            name='tags',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='PBSMMAssetAvailability',
        ),
    ]
