# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20180205_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='object_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Object Type'),
        ),
    ]
