# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_pbsmmasset_object_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmassetimage',
            name='chapters',
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='chapters',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Chapters'),
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='links',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Links'),
        ),
    ]
