# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20180205_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='images',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Images'),
        ),
    ]
