# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_pbsmmasset_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmassetcaption',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='pbsmmassetimage',
            name='asset',
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='content_rating_description',
            field=models.TextField(blank=True, null=True, verbose_name='Content Rating Description'),
        ),
        migrations.AlterField(
            model_name='pbsmmasset',
            name='content_rating',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Rating'),
        ),
        migrations.DeleteModel(
            name='PBSMMAssetCaption',
        ),
        migrations.DeleteModel(
            name='PBSMMAssetImage',
        ),
    ]
