# Generated by Django 5.2.12 on 2026-06-18 10:56

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def link_assets(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Asset = apps.get_model("asset", "Asset")
    content_records = {
        record.content_id: record
        for record in ContentRecord.objects.filter(api_data__data__type="asset")
    }
    assets = list(Asset.objects.filter(object_id__isnull=False))
    for asset in assets:
        asset.mm_content = content_records[asset.object_id]
    Asset.objects.bulk_update(assets, ["mm_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0009_alter_asset_options"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_assets, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="asset",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="can_embed_player",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="geo_profile",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="has_captions",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="images",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="is_excluded_from_dfp",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="json",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="language",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="legacy_tp_media_id",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="links",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="player_code",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="updated_at",
        ),
    ]
