# Generated by Django 6.0.6 on 2026-06-18 18:04


from django.db import (
    migrations,
    models,
)


def fix_asset_json(apps, schema_editor):
    Asset = apps.get_model("asset", "Asset")
    link_prefix = "https://media.services.pbs.org/api/v1/assets"
    assets = Asset.objects.all().annotate(
        data_format=models.Case(
            models.When(
                models.Q(json__has_key="links"),
                then=models.Value("compact"),
            ),
            default=models.Value("full"),
            output_field=models.CharField(),
        ),
    )

    for asset in assets:
        if asset.data_format == "full":
            old_json = asset.json
            content_id = old_json.get("id")
            reformed_json = dict(
                jsonapi=dict(version="1.0"),
                data=old_json,
                meta=dict(type="resource"),
                links=dict(self=f"{link_prefix}/{content_id}/"),
            )
            asset.json = reformed_json
        elif asset.data_format == "compact":
            old_json: dict = asset.json
            links = old_json.pop("links")
            reformed_json = dict(
                jsonapi=dict(version="1.0"),
                data=old_json,
                meta=dict(type="resource"),
                links=links,
            )
            asset.json = reformed_json

    Asset.objects.bulk_update(assets, ["json"])


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0009_alter_asset_options"),
    ]

    operations = [
        migrations.RunPython(fix_asset_json, migrations.RunPython.noop),
    ]
