# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_pbsmmasset_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='geo_platform',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Geo Platform'),
        ),
    ]
