# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_pbsmmasset_geo_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmasset',
            name='geo_platform',
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='geo_profile',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Geo Profile'),
        ),
    ]
