# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_pbsmmasset_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsmmasset',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='pbsmmasset',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='API record modified date', null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='pbsmmasset',
            name='date_last_api_update',
            field=models.DateTimeField(help_text='Not set by API', null=True, verbose_name='Last API Retrieval'),
        ),
    ]
