# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20180206_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='link_to_api_record',
            field=models.URLField(blank=True, help_text='Endpoint to original record from the API', null=True, verbose_name='Link to API Record'),
        ),
    ]
