# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_pbsmmasset_link_to_api_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmasset',
            name='windows',
            field=models.TextField(blank=True, help_text='JSON serialized field', null=True, verbose_name='Windows'),
        ),
    ]
