# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_pbsmmasset_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmasset',
            name='legacy_tp_media_id',
            field=models.BigIntegerField(blank=True, help_text='(Legacy TP Media ID)', null=True, unique=True, verbose_name='COVE ID'),
        ),
        migrations.AlterField(
            model_name='pbsmmasset',
            name='object_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID'),
        ),
    ]
