# Generated by Django 5.2.12 on 2026-06-16 11:39

from django.db import (
    migrations,
    models,
)


def populate_records(apps, schema_editor):
    Asset = apps.get_model("asset", "Asset")
    Episode = apps.get_model("episode", "Episode")
    Season = apps.get_model("season", "Season")
    Special = apps.get_model("special", "Special")
    Show = apps.get_model("show", "Show")
    Franchise = apps.get_model("franchise", "Franchise")
    ContentRecord = apps.get_model("record", "ContentRecord")

    batch_data = [
        ContentRecord(
            content_id=franchise.object_id,
            api_data=franchise.json,
            last_api_status=franchise.last_api_status,
        )
        for franchise in Franchise.objects.filter(object_id__isnull=False)
    ]
    batch_data += [
        ContentRecord(
            content_id=show.object_id,
            api_data=show.json,
            last_api_status=show.last_api_status,
        )
        for show in Show.objects.filter(object_id__isnull=False)
    ]
    batch_data += [
        ContentRecord(
            content_id=season.object_id,
            api_data=season.json,
            last_api_status=season.last_api_status,
        )
        for season in Season.objects.filter(object_id__isnull=False)
    ]
    batch_data += [
        ContentRecord(
            content_id=special.object_id,
            api_data=special.json,
            last_api_status=special.last_api_status,
        )
        for special in Special.objects.filter(object_id__isnull=False)
    ]
    batch_data += [
        ContentRecord(
            content_id=episode.object_id,
            api_data=episode.json,
            last_api_status=episode.last_api_status,
        )
        for episode in Episode.objects.filter(object_id__isnull=False)
    ]
    batch_data += [
        ContentRecord(
            content_id=asset.object_id,
            api_data=asset.json,
            last_api_status=asset.last_api_status,
        )
        for asset in Asset.objects.filter(object_id__isnull=False)
    ]
    ContentRecord.objects.bulk_create(batch_data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0010_fix_asset_json"),
        ("episode", "0018_auto_increment_ordinal"),
        ("franchise", "0002_alter_franchise_genre_alter_franchise_images_and_more"),
        ("season", "0018_auto_increment_ordinal"),
        ("show", "0013_remove_show_season_ordinal_alter_show_ordinal_season"),
        ("special", "0014_special_provisional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRecord",
            fields=[
                ("content_id", models.UUIDField(primary_key=True, serialize=False)),
                ("api_data", models.JSONField()),
                (
                    "last_api_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Last API Status"
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_records, migrations.RunPython.noop),
    ]
