# Generated by Django 6.0.5 on 2026-07-06 18:50

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrecord",
            name="deleted",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set from the PBS changelog timestamp when the object was deleted upstream.",
                null=True,
                verbose_name="Deleted",
            ),
        ),
    ]
