# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbsmmapi', '0004_pbsmmfranchise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pbsmmepisode',
            options={'verbose_name': 'PBS Media Manager Episode', 'verbose_name_plural': 'PBS Media Manager Episodes'},
        ),
        migrations.AlterModelOptions(
            name='pbsmmfranchise',
            options={'verbose_name': 'PBS Media Manager Franchise', 'verbose_name_plural': 'PBS Media Manager Franchises'},
        ),
    ]
