# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbsmmapi', '0006_assetremoteassetrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEpisodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_link', to='pbsmmapi.PBSMMAsset')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_list', to='pbsmmapi.PBSMMEpisode')),
            ],
        ),
    ]
