# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbsmmapi', '0007_assetepisoderelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmepisode',
            name='ingest_related_assets',
            field=models.BooleanField(default=False, help_text='If true, then will scrape assets from the PBSMM API on save()', verbose_name='Ingest Related Assets'),
        ),
        migrations.AlterField(
            model_name='assetepisoderelation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_episode', to='pbsmmapi.PBSMMAsset'),
        ),
        migrations.AlterField(
            model_name='assetepisoderelation',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_asset_list', to='pbsmmapi.PBSMMEpisode'),
        ),
    ]
