# Generated by Django 6.0.5 on 2026-07-02 13:03

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0002_alter_franchise_genre_alter_franchise_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="deleted",
            field=models.DateTimeField(
                blank=True,
                help_text="Set from the PBS changelog timestamp when the object was deleted upstream.",
                null=True,
                verbose_name="Deleted",
            ),
        ),
    ]
