# Generated by Django 5.2.12 on 2026-06-17 11:59

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


def link_franchises(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Franchise = apps.get_model("franchise", "Franchise")
    content_record_map = dict(
        ContentRecord.objects.filter(api_data__data__type="franchise").values_list(
            "content_id", "pk"
        )
    )

    batch_size = 1000
    batch = []

    for franchise in Franchise.objects.filter(object_id__isnull=False).iterator(
        chunk_size=batch_size
    ):
        content_record_pk = content_record_map.get(franchise.object_id)
        if content_record_pk:
            franchise.mm_content_id = content_record_pk
            batch.append(franchise)
            if len(batch) >= batch_size:
                Franchise.objects.bulk_update(batch, ["mm_content"])
                batch.clear()

    if batch:
        Franchise.objects.bulk_update(batch, ["mm_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("franchise", "0002_alter_franchise_genre_alter_franchise_images_and_more"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RunPython(link_franchises, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="franchise",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="can_embed_player",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="ga_event",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="ga_page",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="hashtag",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="images",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="is_excluded_from_dfp",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="json",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="links",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="updated_at",
        ),
    ]
