# Generated by Django 5.2.12 on 2026-06-17 11:59

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


def link_franchises(apps, schema_editor):
    ContentRecord = apps.get_model("record", "ContentRecord")
    Franchise = apps.get_model("franchise", "Franchise")
    content_records = {
        record.content_id: record
        for record in ContentRecord.objects.filter(api_data__data__type="franchise")
    }
    franchises = list(Franchise.objects.filter(object_id__isnull=False))
    for franchise in franchises:
        franchise.mm_content = content_records[franchise.object_id]
    Franchise.objects.bulk_update(franchises, ["mm_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0002_alter_franchise_genre_alter_franchise_images_and_more"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="mm_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record.contentrecord",
            ),
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="api_endpoint",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="can_embed_player",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="date_last_api_update",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="funder_message",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="ga_event",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="ga_page",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="hashtag",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="images",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="is_excluded_from_dfp",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="json",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="last_api_status",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="links",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="nola",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="premiered_on",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="title_sortable",
        ),
        migrations.RemoveField(
            model_name="franchise",
            name="updated_at",
        ),
    ]
