# Generated by Django 5.2.17 on 2026-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0003_remove_franchise_api_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="franchise",
            options={
                "base_manager_name": "objects",
                "verbose_name": "PBS MM Franchise",
                "verbose_name_plural": "PBS MM Franchises",
            },
        ),
    ]
