name: CI

on:
  push:
    branches:
      - main
      - v1_release_prep
    tags:
      - '**'

env:
  COLUMNS: 150
  UV_FROZEN: true
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Installing pip is required for the pre-commit action:
        run: |
          uv sync --dev
          uv pip install pip

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose
        env:
          SKIP: no-commit-to-branch

  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync

      - name: Build library
        run: uv build
